[package]
name = "sel4_cspace"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
sel4_common = { git = "https://github.com/reL4team2/sel4_common.git", branch = "master" }
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }

[features]
KERNEL_MCS = []